let arr = [
    {
        "menuId": 1,
        "menuName": "顶级菜单1",
        "menuExplain": "123",
        "path": "/path",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": null,
        "tsysMenus": [
            {
                "menuId": 5,
                "menuName": "子集菜单4",
                "menuExplain": "123",
                "path": "/path/path1",
                "parentId": 1,
                "flag": "0",
                "enabled": "0",
                "createdName": null,
                "createdTime": null,
                "updatedTime": null,
                "updatedName": null,
                "isFlag": "1",
                "select": false,
                "menuType": null,
                "tsysMenus": [
                    {
                        "menuId": 10,
                        "menuName": "子集菜单8",
                        "menuExplain": "123",
                        "path": "/path/path1122",
                        "parentId": 5,
                        "flag": "0",
                        "enabled": "0",
                        "createdName": null,
                        "createdTime": null,
                        "updatedTime": null,
                        "updatedName": null,
                        "isFlag": "1",
                        "select": false,
                        "menuType": null,
                        "tsysMenus": null
                    }
                ]
            },
            {
                "menuId": 6,
                "menuName": "子集菜单1",
                "menuExplain": "123",
                "path": "/path/path2",
                "parentId": 1,
                "flag": "0",
                "enabled": "0",
                "createdName": null,
                "createdTime": null,
                "updatedTime": null,
                "updatedName": null,
                "isFlag": "1",
                "select": false,
                "menuType": null,
                "tsysMenus": null
            },
            {
                "menuId": 7,
                "menuName": "子集菜单3",
                "menuExplain": "123",
                "path": "/path/path3",
                "parentId": 1,
                "flag": "0",
                "enabled": "0",
                "createdName": null,
                "createdTime": null,
                "updatedTime": null,
                "updatedName": null,
                "isFlag": "1",
                "select": false,
                "menuType": null,
                "tsysMenus": [
                    {
                        "menuId": 8,
                        "menuName": "子集菜单4",
                        "menuExplain": "123",
                        "path": "/path/path12",
                        "parentId": 7,
                        "flag": "0",
                        "enabled": "0",
                        "createdName": null,
                        "createdTime": null,
                        "updatedTime": null,
                        "updatedName": null,
                        "isFlag": "1",
                        "select": false,
                        "menuType": null,
                        "tsysMenus": [
                            {
                                "menuId": 9,
                                "menuName": "子集菜单5",
                                "menuExplain": "123",
                                "path": "/path/path122",
                                "parentId": 8,
                                "flag": "0",
                                "enabled": "0",
                                "createdName": null,
                                "createdTime": null,
                                "updatedTime": null,
                                "updatedName": null,
                                "isFlag": "1",
                                "select": false,
                                "menuType": null,
                                "tsysMenus": null
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "menuId": 2,
        "menuName": "顶级菜单2",
        "menuExplain": "123",
        "path": "/path2",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": null,
        "tsysMenus": null
    },
    {
        "menuId": 3,
        "menuName": "顶级菜单3",
        "menuExplain": "123",
        "path": "/path3",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": null,
        "tsysMenus": null
    },
    {
        "menuId": 4,
        "menuName": "顶级菜单4",
        "menuExplain": "123",
        "path": "/path4",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": null,
        "tsysMenus": null
    },
    {
        "menuId": 11,
        "menuName": "首页",
        "menuExplain": "home",
        "path": "/home",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null
    },
    {
        "menuId": 12,
        "menuName": "角色管理",
        "menuExplain": "domain",
        "path": "/role",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null,
        buttons: [
            { path: "/role/add", name: "新增角色", selece: false },
            { path: "/role/edit", name: "编辑", selece: false },
            { path: "/role/disable", name: "禁用", selece: false },
            { path: "/role/enable", name: "启用", selece: false },
            { path: "/role/detail", name: "查看", selece: false },
            { path: "/role/delete", name: "删除", selece: false },
            { path: "/role/menu", name: "菜单配置", selece: false },
            { path: "/role/data", name: "数据权限", selece: false },
        ]
    },
    {
        "menuId": 13,
        "menuName": "账号管理",
        "menuExplain": "domain",
        "path": "/account",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null,
        buttons: [
            { path: "/account/add", name: "新增账号", selece: false },
            { path: "/account/edit", name: "编辑", selece: false },
            { path: "/account/disable", name: "禁用", selece: false },
            { path: "/account/enable", name: "启用", selece: false },
            { path: "/account/detail", name: "查看", selece: false },
            { path: "/account/del", name: "删除", selece: false },
            { path: "/account/reset", name: "重置密码", selece: false },
            { path: "/account/setrole", name: "角色配置", selece: false },
        ]
    },
    {
        "menuId": 14,
        "menuName": "字典管理",
        "menuExplain": "domain",
        "path": "/dictionary",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null,
        buttons: [
            { path: "/dictionary/add", name: "新增字典", selece: false },
            { path: "/dictionary/edit", name: "编辑", selece: false },
            { path: "/dictionary/disable", name: "禁用", selece: false },
            { path: "/dictionary/enable", name: "启用", selece: false },
            { path: "/dictionary/detail", name: "查看", selece: false },
            { path: "/dictionary/del", name: "删除", selece: false },
        ]
    },
    {
        "menuId": 15,
        "menuName": "设备管理",
        "menuExplain": "domain",
        "path": "/mydevice",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null,
        buttons: [
            { path: "/mydevice/add", name: "新增设备", selece: false },
            { path: "/mydevice/edit", name: "编辑", selece: false },
            { path: "/mydevice/disable", name: "禁用", selece: false },
            { path: "/mydevice/enable", name: "启用", selece: false },
            { path: "/mydevice/detail", name: "查看", selece: false },
            { path: "/mydevice/up", name: "导入", selece: false },
            { path: "/mydevice/down", name: "导出", selece: false },
            { path: "/mydevice/del", name: "删除", selece: false },
        ]
    },
    {
        "menuId": 16,
        "menuName": "人员管理",
        "menuExplain": "domain",
        "path": "/staff",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null,
        buttons: [
            { path: "/staff/add", name: "新增人员", selece: false },
            { path: "/staff/edit", name: "编辑", selece: false },
            { path: "/staff/disable", name: "禁用", selece: false },
            { path: "/staff/enable", name: "启用", selece: false },
            { path: "/staff/detail", name: "查看", selece: false },
            { path: "/staff/up", name: "导入", selece: false },
            { path: "/staff/del", name: "删除", selece: false },
        ]
    },
    {
        "menuId": 17,
        "menuName": "班别管理",
        "menuExplain": "domain",
        "path": "/class",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null,
        buttons: [
            { path: "/class/down", name: "导出", selece: false },
            { path: "/class/add", name: "新增班别", selece: false },
            { path: "/class/edit", name: "编辑", selece: false },
            { path: "/class/disable", name: "禁用", selece: false },
            { path: "/class/enable", name: "启用", selece: false },
            { path: "/class/detail", name: "查看", selece: false },
            { path: "/class/member", name: "组员管理", selece: false },
            { path: "/class/del", name: "删除", selece: false },
        ]
    },
    {
        "menuId": 18,
        "menuName": "规则链库",
        "menuExplain": "settings_ethernet",
        "path": "/ruleChains",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null,

    },
    {
        "menuId": 19,
        "menuName": "订单管理",
        "menuExplain": "bookmarks",
        "path": "/order",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "0",
        "select": true,
        "menuType": "toggle",
        "tsysMenus": [
            {
                "menuId": 33,
                "menuName": "订单列表",
                "menuExplain": "bookmarks",
                "path": "/order/list",
                "parentId": 19,
                "flag": "0",
                "enabled": "0",
                "createdName": null,
                "createdTime": null,
                "updatedTime": null,
                "updatedName": null,
                "isFlag": "0",
                "select": true,
                "menuType": "link",
                "tsysMenus": null,
                buttons: [
                    { path: "/order/list/up", name: "导出", selece: false },
                    { path: "/order/list/start", name: "接单开工", selece: false },
                    { path: "/order/list/moreStart", name: "批量接单", selece: false },
                ]

            }
        ]
    },
    {
        "menuId": 20,
        "menuName": "工艺路线管理",
        "menuExplain": "bookmarks",
        "path": "/technological",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "toggle",
        "tsysMenus": [
            {
                "menuId": 34,
                "menuName": "工艺路线",
                "menuExplain": "bookmarks",
                "path": "/technological/processRoute",
                "parentId": 20,
                "flag": "0",
                "enabled": "0",
                "createdName": null,
                "createdTime": null,
                "updatedTime": null,
                "updatedName": null,
                "isFlag": "1",
                "select": false,
                "menuType": "link",
                "tsysMenus": null,
                buttons: [
                    { path: "/technological/processRoute/add", name: "新增工艺路线", selece: false },
                    { path: "/technological/processRoute/bind", name: "产品绑定", selece: false },
                    { path: "/technological/processRoute/disable", name: "禁用", selece: false },
                    { path: "/technological/processRoute/enable", name: "启用", selece: false },
                    { path: "/technological/processRoute/edit", name: "编辑", selece: false },
                    { path: "/technological/processRoute/del", name: "删除", selece: false }
                ]
            },
            {
                "menuId": 35,
                "menuName": "工序管理",
                "menuExplain": "bookmarks",
                "path": "/technological/processManage",
                "parentId": 20,
                "flag": "0",
                "enabled": "0",
                "createdName": null,
                "createdTime": null,
                "updatedTime": null,
                "updatedName": null,
                "isFlag": "1",
                "select": false,
                "menuType": "link",
                "tsysMenus": null,
                buttons: [
                    { path: "/technological/processManage/set", name: "工序设置", selece: false },
                    { path: "/technological/processManage/add", name: "新增工序", selece: false },
                    { path: "/technological/processManage/edit", name: "编辑", selece: false },
                    { path: "/technological/processManage/disable", name: "禁用", selece: false },
                    { path: "/technological/processManage/enable", name: "启用", selece: false },
                    { path: "/technological/processManage/del", name: "删除", selece: false }
                ]
            }
        ]
    },
    {
        "menuId": 21,
        "menuName": "资产",
        "menuExplain": "domain",
        "path": "/assets",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null
    },
    {
        "menuId": 22,
        "menuName": "设备",
        "menuExplain": "devices_other",
        "path": "/devices",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null
    },
    {
        "menuId": 23,
        "menuName": "设备配置",
        "menuExplain": "mdi:alpha-d-box",
        "path": "/deviceProfiles",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null
    },
    {
        "menuId": 24,
        "menuName": "OTA升级",
        "menuExplain": "memory",
        "path": "/otaUpdates",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null
    },
    {
        "menuId": 25,
        "menuName": "实体视图",
        "menuExplain": "view_quilt",
        "path": "/entityViews",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null
    },
    {
        "menuId": 26,
        "menuName": "Edge instances",
        "menuExplain": "router",
        "path": "/edgeInstances",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null
    },
    {
        "menuId": 27,
        "menuName": "Edge management",
        "menuExplain": "settings_input_antenna",
        "path": "/edgeManagement",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "toggle",
        "tsysMenus": [
            {
                "menuId": 36,
                "menuName": "Rule Chain templates",
                "menuExplain": "settings_ethernet",
                "path": "/edgeManagement/ruleChains",
                "parentId": 27,
                "flag": "0",
                "enabled": "0",
                "createdName": null,
                "createdTime": null,
                "updatedTime": null,
                "updatedName": null,
                "isFlag": "1",
                "select": false,
                "menuType": "link",
                "tsysMenus": null
            }
        ]
    },
    {
        "menuId": 28,
        "menuName": "部件库",
        "menuExplain": "now_widgets",
        "path": "/widgets-bundles",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null
    },
    {
        "menuId": 29,
        "menuName": "仪表板库",
        "menuExplain": "dashboards",
        "path": "/dashboards",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null
    },
    {
        "menuId": 30,
        "menuName": "审计日志",
        "menuExplain": "domain",
        "path": "/assets",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null
    },
    {
        "menuId": 31,
        "menuName": "Api 使用统计",
        "menuExplain": "insert_chart",
        "path": "/usage",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null
    },
    {
        "menuId": 32,
        "menuName": "系统设置",
        "menuExplain": "settings",
        "path": "/settings",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "toggle",
        "tsysMenus": [
            {
                "menuId": 37,
                "menuName": "首页设置",
                "menuExplain": "settings_applications",
                "path": "/settings/home",
                "parentId": 32,
                "flag": "0",
                "enabled": "0",
                "createdName": null,
                "createdTime": null,
                "updatedTime": null,
                "updatedName": null,
                "isFlag": "1",
                "select": false,
                "menuType": "link",
                "tsysMenus": null
            },
            {
                "menuId": 38,
                "menuName": "资源库",
                "menuExplain": "folder",
                "path": "/settings/resources-library",
                "parentId": 32,
                "flag": "0",
                "enabled": "0",
                "createdName": null,
                "createdTime": null,
                "updatedTime": null,
                "updatedName": null,
                "isFlag": "1",
                "select": false,
                "menuType": "link",
                "tsysMenus": null
            }
        ]
    },
    {
        "menuId": 39,
        "menuName": "物料管理",
        "menuExplain": "domain",
        "path": "/material",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null,
        buttons: [
            { path:"/material/add", name: "新增物料", selece: false },
            { path:"/material/edit", name: "编辑", selece: false },
            { path:"/material/disable", name: "禁用", selece: false },
            { path:"/material/enable", name: "启用", selece: false },
            { path:"/material/del", name: "删除", selece: false },
            { path:"/material/sync", name: "同步", selece: false },
        ]
    },
    {
        "menuId": 40,
        "menuName": "料框管理",
        "menuExplain": "domain",
        "path": "/basketManage",
        "parentId": 0,
        "flag": "0",
        "enabled": "0",
        "createdName": null,
        "createdTime": null,
        "updatedTime": null,
        "updatedName": null,
        "isFlag": "1",
        "select": false,
        "menuType": "link",
        "tsysMenus": null,
        buttons: [
            { path:"/basketManage/add", name: "新增料框", selece: false },
            { path:"/basketManage/edit", name: "编辑", selece: false },
            { path:"/basketManage/disable", name: "禁用", selece: false },
            { path:"/basketManage/enable", name: "启用", selece: false },
            { path:"/basketManage/del", name: "删除", selece: false },
            { path:"/basketManage/up", name: "导入料框", selece: false },
            { path:"/basketManage/down", name: "导出二维码", selece: false },
        ]
    }
]